-- Add food products for Salvo & Charles Saunders
INSERT INTO public.products (name, category, unit, current_price, reorder_point, supplier_id) VALUES
('Nachos 12x450g', 'Food', 'case', 32.84, 1, 'salvo-charles'),
('Pizza Bases 1x40', 'Food', 'box', 24.40, 2, 'salvo-charles'),
('Pizza Sauce', 'Food', 'tin', 6.01, 2, 'salvo-charles'),
('Cubed Chicken 2.5kg', 'Food', 'bag', 16.99, 1, 'salvo-charles'),
('Pepperoni Slices 1kg', 'Food', 'box', 9.50, 2, 'salvo-charles'),
('80/20 Mixed Cheese', 'Food', 'bag', 12.70, 5, 'salvo-charles'),
('Pulled Pork 500g', 'Food', 'pack', 6.07, 3, 'salvo-charles'),
('Diced Mixed Peppers 1kg', 'Food', 'bag', 2.73, 2, 'salvo-charles'),
('Sweet Corn', 'Food', 'bag', 2.51, 2, 'salvo-charles'),
('Jalapenos 3kg', 'Food', 'tin', 4.69, 1, 'salvo-charles'),
('Pineapple 6x820g', 'Food', 'pack', 17.74, 1, 'salvo-charles'),
('Fries 10kg', 'Food', 'box', 16.32, 2, 'salvo-charles'),
('Sweet Chilli', 'Condiments', 'bag', 3.16, 2, 'salvo-charles'),
('Salsa 2.4kg', 'Condiments', 'jar', 6.82, 1, 'salvo-charles'),
('Ketchup 1L', 'Condiments', 'bottle', 2.29, 2, 'salvo-charles'),
('Guacamole 500g', 'Condiments', 'pot', 3.57, 2, 'salvo-charles'),
('Sour Cream & Chive', 'Condiments', 'jar', 11.05, 1, 'salvo-charles'),
('Garlic Mayo 1L', 'Condiments', 'bottle', 2.74, 2, 'salvo-charles'),
('Mayonnaise 1L', 'Condiments', 'bottle', 2.60, 2, 'salvo-charles'),
('BBQ Sauce 2.5L', 'Condiments', 'bottle', 2.45, 2, 'salvo-charles'),
('Chilli Flakes 260g', 'Seasonings', 'pot', 4.97, 1, 'salvo-charles'),
('Mixed Herbs 150g', 'Seasonings', 'pot', 2.64, 1, 'salvo-charles'),
('Mustard 1L', 'Condiments', 'bottle', 2.35, 1, 'salvo-charles'),
('Ice', 'Other', 'case', 6.50, 4, 'salvo-charles');