// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lauofylztqntozfywwru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhdW9meWx6dHFudG96Znl3d3J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTE1MzUsImV4cCI6MjA2NzcyNzUzNX0.Y3MpXMHq1HNWBnnz-TZ1ILG4hHh24PcnVBVsV2qGckc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});